#pragma once

// Debug
#define DEBUG_TX_PIN GPIO_NUM_43
#define DEBUG_RX_PIN GPIO_NUM_44

// Display
#define DISP_SCK_PIN GPIO_NUM_5
#define DISP_MOSI_PIN GPIO_NUM_8
#define DISP_CS_PIN GPIO_NUM_7
#define DISP_DC_PIN GPIO_NUM_6
#define DISP_RST_PIN GPIO_NUM_4
#define DISP_BL_PIN GPIO_NUM_9

// GNSS
#define GNSS_TX_PIN GPIO_NUM_17
#define GNSS_RX_PIN GPIO_NUM_18
#define GPS_LDO_EN_PIN GPIO_NUM_14

// I2C
#define I2C_SCL_PIN GPIO_NUM_39
#define I2C_SDA_PIN GPIO_NUM_40

// Sensor Interrupts
#define ACCGYRO_INT_PIN GPIO_NUM_41
#define MAG_INT_PIN GPIO_NUM_42
#define PRESS_INT_PIN GPIO_NUM_13

// SD Card
#define SD_D1_PIN GPIO_NUM_38
#define SD_D0_PIN GPIO_NUM_37
#define SD_CLK_PIN GPIO_NUM_36
#define SD_CMD_PIN GPIO_NUM_35
#define SD_D2_PIN GPIO_NUM_34
#define SD_D3_PIN GPIO_NUM_33

// Input
#define ENC_A_PIN GPIO_NUM_1
#define ENC_B_PIN GPIO_NUM_3
#define KEY_MAIN_PIN GPIO_NUM_2

// Power Management
#define BAT_ADC_PIN GPIO_NUM_12
#define CHRG_STATUS_PIN GPIO_NUM_21
